### ISSUE TITLE
Where did you learn the process of how to detect a SP ?

### ISSUE THREAD

**Issue by simonprovost** [xaviervilla/sleep-paralysis-interrupt#1]
**Hello**,

Do you have any links or sources of few thesis that you've learned before creating your classifier to know when the "patient" have held a SP with an X/Y/Z axis ? I know the process to know when the "patient" are awake or asleep with some algorithm like sadeh et al and so on but for sleep paralysis I'm currently lost.

It's school/job purpose or just personal purpose that you study/work on this topic ?

Great project then ! I am a student which is currently working on sleep disorder with computer science in help.

**Comment by xaviervilla** [comment]
> **Hello**,
> 
> Do you have any links or sources of few thesis that you've learned before creating your classifier to know when the "patient" have held a SP with an X/Y/Z axis ? I know the process to know when the "patient" are awake or asleep with some algorithm like sadeh et al and so on but for sleep paralysis I'm currently lost.
> 
> It's school/job purpose or just personal purpose that you study/work on this topic ?
> 
> Great project then ! I am a student which is currently working on sleep disorder with computer science in help.

Sorry for the late response, somehow I never saw your comment. I did no research prior to starting. I suffer sleep paralysis very frequently. Sometimes I have it every day for weeks, sometimes I don't get it for a month. I came up with the idea because when I get sleep paralysis, I start breathing heavily so that my Fiancee can wake me. She is able to detect when I have SP, so I thought "If she can do it, so can a computer". I was doing this project for credit at my university. I was an undergraduate, so I wasn't able to devote a lot of time to research, but I can tell you this device works very very well! I want to make a youtube video on the project soon.

**Comment by xaviervilla** [comment]
Forgive me, my level of academic research is very inexperienced, but I just uploaded my final report that contains the story of my progress on how I worked on this project. Feel free to take a look and reach out if you have questions.

**Comment by simonprovost** [comment]
Thank you for these information, I will ask you more as soon as we are at your level, we beginning a project in that field as well and we search what people do in github to be inspirate.

So, very well report we like it it's a beautiful initiative and simply to read !!

Have a great weekend. :crown:
